project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd 
      - text: "Publications"
        href: publications.qmd
      - text: "Blog"
        href: posts.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
